name: Debricked SCA

on: [push]

jobs:
  debricked:
    runs-on: ubuntu-latest

    container:
      image: debricked/cli:latest-resolution-debian
      # Choosing the right container image for your scan can be important. 
      # All Debricked images are here: https://hub.docker.com/r/debricked/cli

      # Resolution images (contains "resolution" in tag) are bigger, but comes with a lot of pre-installed package managers: 
      # Here are the dockerfiles: https://github.com/debricked/cli/tree/main/build/docker
      # This is the easiest way to integrate, but it may be better 
      # to run debricked scans in you build images. 

      # You can choose between debian and alpine images, where we do alpine by default. 
      # We recommend to use debian images for scanning Python projects, as the scanner will not 
      # need to compile some common c-based dependencies like pandas. 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Call graph generation
        uses: debricked/actions/callgraph@v4
      - name: Scan everything
        run: |
          debricked scan --no-fingerprint=true
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
          
      # Here I make demonstrate how to do two separate scans with debricked in different parts of the repo
      # This will create two separate repos in the debricked tool, and can be managed
      # with different policies etc. 
      # You can also split these out to two separate actions to make the results easier to consume visually. 
      - name: Scan web service
        if: success() || failure() ## Run this scan even though the previous scan resulted in a pipeline failure
        run: |
          debricked scan web/ -r web-service
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
      - name: Scan api service
        if: success() || failure() ## Run this scan even though the previous scan resulted in a pipeline failure
        run: |
          debricked scan src/ -r api-service
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}

  vulnerabilities-scan-staging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: debricked/actions/callgraph@v4
      - uses: actions/upload-artifact@v4
        with:
          name: call graph file
          path: debricked-call-graph.java
      - uses: debricked/actions@v4
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN_STAGING }}
          DEBRICKED_URI: 'https://staging.debricked.com'


  vulnerabilities-scan-review:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: debricked/actions/callgraph@v4
      - uses: actions/upload-artifact@v4
        with:
          name: sbom-report
          path: debricked-call-graph.java
      - uses: debricked/actions@v4
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN_STAGING }}
          DEBRICKED_URI: 'https://review-7791-fix-a-3p3ieb.review.debricked.dev'
